### ISSUE TITLE
Nondeterministic error reading `.tar.gz` (reaches `go test` timeout)

### ISSUE THREAD

**Issue by Integralist** [mholt/archiver#325]
> **NOTE**: I've raised a similar issue in one of your project dependency repos [here](https://github.com/klauspost/pgzip/issues/49).
> Just in case the issue isn't with this package but the dependency.

## What version of the package or command are you using?
`v3.5.1`

## What are you trying to do?
Read a `.tar.gz` file and check that specific files are contained within it.

## What steps did you take?
You can find a copy of the archive file here: https://github.com/fastly/cli/blob/main/pkg/commands/compute/testdata/deploy/pkg/package.tar.gz

Here is the code that attempts to validate the file:
https://github.com/fastly/cli/blob/main/pkg/commands/compute/validate.go#L51-L105

## What did you expect to happen, and what actually happened instead?
I noticed that my test suite would fail nondeterministically due to a `go test` timeout panic. 
The cause of the timeout appears to be related to the archiver sub-dependency: 
https://github.com/klauspost/pgzip

If I run my test suite with a non default `-count` value of `20` (default is 1), then I can reliably get the test suite to panic. What happens is the archive file is read and one of the tests will eventually try to read the file and fail. The tests are not using `t.Parallel()` so there is no need to synchronise access to the archive file.

Below is the test run error stack trace (you'll notice that there are two tests that run and they pass multiple times before nondeterministically failing with a panic)...

> **NOTE**: From what I can see our code calls `tar.Read()` [here](https://github.com/fastly/cli/blob/main/pkg/commands/compute/validate.go#L78) which then triggers the panic down in `klauspost/pgzip.(*Reader).Read` [here](https://github.com/klauspost/pgzip/blob/v1.2.4/gunzip.go#L451).

```
--- PASS: TestDeploy (24.79s)
    --- PASS: TestDeploy/service_domain_error (19.51s)
    --- PASS: TestDeploy/service_backend_error (5.20s)

=== RUN   TestDeploy
=== RUN   TestDeploy/service_domain_error
panic: test timed out after 30s

goroutine 153 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:1788 +0xbb
created by time.goFunc
        /usr/local/go/src/time/sleep.go:180 +0x4a

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00050dba0, {0x1ffd734, 0xa}, 0x203eae0)
        /usr/local/go/src/testing/testing.go:1307 +0x752
testing.runTests.func1(0x0)
        /usr/local/go/src/testing/testing.go:1598 +0x9a
testing.tRunner(0xc00050dba0, 0xc0000e3bf8)
        /usr/local/go/src/testing/testing.go:1259 +0x230
testing.runTests(0xc00029c200, {0x28cbe60, 0x12, 0x12}, {0x0, 0xc00028c840, 0x28dc3a0})
        /usr/local/go/src/testing/testing.go:1596 +0x7cb
testing.(*M).Run(0xc00029c200)
        /usr/local/go/src/testing/testing.go:1504 +0x9d2
main.main()
        _testmain.go:79 +0x22c

goroutine 150 [chan receive]:
testing.(*T).Run(0xc00050dd40, {0x200777d, 0x14}, 0xc00027cf60)
        /usr/local/go/src/testing/testing.go:1307 +0x752
github.com/fastly/cli/pkg/commands/compute_test.TestDeploy(0xc00050dd40)
        /Users/integralist/Code/fastly/cli-main-branch/pkg/commands/compute/deploy_test.go:1262 +0x9ec9
testing.tRunner(0xc00050dd40, 0x203eae0)
        /usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1306 +0x727

goroutine 151 [chan receive]:
github.com/klauspost/pgzip.(*Reader).Read(0xc000613180, {0xc000344000, 0x28c5540, 0x2000})
        /Users/integralist/Code/fastly/cli-main-branch/vendor/github.com/klauspost/pgzip/gunzip.go:451 +0x134
io.(*LimitedReader).Read(0xc00000e378, {0xc000344000, 0x2000, 0x2000})
        /usr/local/go/src/io/io.go:473 +0xc6
io.discard.ReadFrom({}, {0x2215c40, 0xc00000e378})
        /usr/local/go/src/io/io.go:598 +0x92
io.copyBuffer({0x2216d00, 0x290d960}, {0x2215c40, 0xc00000e378}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:409 +0x1c3
io.Copy(...)
        /usr/local/go/src/io/io.go:382
io.CopyN({0x2216d00, 0x290d960}, {0xc584120, 0xc000613180}, 0x22113a0)
        /usr/local/go/src/io/io.go:358 +0xcc
archive/tar.discard({0xc584120, 0xc000613180}, 0x22113a0)
        /usr/local/go/src/archive/tar/reader.go:852 +0x150
archive/tar.(*Reader).next(0xc0000ecd80)
        /usr/local/go/src/archive/tar/reader.go:68 +0xef
archive/tar.(*Reader).Next(0xc0000ecd80)
        /usr/local/go/src/archive/tar/reader.go:51 +0x53
github.com/mholt/archiver/v3.(*Tar).Read(0xc00060e940)
        /Users/integralist/Code/fastly/cli-main-branch/vendor/github.com/mholt/archiver/v3/tar.go:441 +0xa5
github.com/fastly/cli/pkg/commands/compute.validate({0xc00015cba0, 0x12})
        /Users/integralist/Code/fastly/cli-main-branch/pkg/commands/compute/validate.go:78 +0x54d
github.com/fastly/cli/pkg/commands/compute.validatePackage({{{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, 0x2, ...}, ...}, ...)
        /Users/integralist/Code/fastly/cli-main-branch/pkg/commands/compute/deploy.go:414 +0x650
github.com/fastly/cli/pkg/commands/compute.(*DeployCommand).Exec(0xc0000b24e0, {0x2216220, 0xc00008b420}, {0x2215040, 0xc00027d050})
        /Users/integralist/Code/fastly/cli-main-branch/pkg/commands/compute/deploy.go:106 +0x5d8
github.com/fastly/cli/pkg/app.Run({0xc0004fff80, {0xc00016e7c0, 0x4, 0x4}, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...})
        /Users/integralist/Code/fastly/cli-main-branch/pkg/app/run.go:171 +0x1f95
github.com/fastly/cli/pkg/commands/compute_test.TestDeploy.func1(0xc000183520)
        /Users/integralist/Code/fastly/cli-main-branch/pkg/commands/compute/deploy_test.go:1352 +0x1165
testing.tRunner(0xc000183520, 0xc00027cf60)
        /usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1306 +0x727

goroutine 152 [running]:
        goroutine running on other thread; stack unavailable
created by github.com/klauspost/pgzip.(*Reader).doReadAhead
        /Users/integralist/Code/fastly/cli-main-branch/vendor/github.com/klauspost/pgzip/gunzip.go:379 +0x528
FAIL    github.com/fastly/cli/pkg/commands/compute      31.614s
?       github.com/fastly/cli/pkg/commands/compute/setup        [no test files]
FAIL
make: *** [test] Error 1
```

## How do you think this should be fixed?
I'm not sure because Archiver is already using the latest version of pgzip (`1.2.5`). 
Ideally pgzip shouldn't panic unexpectedly.
But I suspect there's something I (or `pgzip`) is doing wrong.

**Comment by mholt** [comment]
Hmm, have you considered opening this issue in the pgzip repository? I don't know anything about pgzip's internals. (Nor am I really maintaining Archiver v3 anymore, as v4 is in beta now.)

But thanks for the good repro steps, I'm sure they'll be useful to the right person to help troubleshoot!

**Comment by mholt** [comment]
Thanks. Keep me posted, if it affects archiver v4 I will want to make necessary changes. Klaus is brilliant and really great about responding so with your test case I'm not too worried!
